### PR TITLE
Fixed `events` variable error.

### PR DESCRIPTION
**Pull request by troyanryller**

### CODE REVIEW

**Comment by rstormsf** [comment]
does it fixes #3 ? Have u seen similar issue? can't get it work at all

**Comment by rstormsf** [comment]
Installed your branch in my Gemfile:
`gem 'rails_admin_aasm', :git => 'https://github.com/troyanryller/rails_admin_aasm/', :branch => 'feature/fix-undefined-events-variable'`
still get this same issue. Any help?

**Comment by troyanryller** [comment]
@rstormsf  It should be fixed after adding `attr_accessor :my-state-field-name_event` to your model. Also mention about it in readme.md

**Comment by rstormsf** [comment]
:-( Can't understand how to get this work. What should `state_event` method return?

**Comment by troyanryller** [comment]
@rstormsf nothing, it should be only like temporary variable for model, so in model:

``` ruby
attr_accessor :state_event
```

should fix your problem. If u have other name for aasm field then u need to specify different accessor, for example i got `status` field for aasm statuses, so i add `attr_accessor :status_event` to my model and 

``` ruby
    rails_admin do
      list do
        field :account
        field :status, :state
        ....
```

**Comment by zcpdog** [comment]
Hi @troyanryller  thanks for contribution, I think this pr is duplicated with https://github.com/zcpdog/rails_admin_aasm/pull/1  what do you think

**Comment by troyanryller** [comment]
@zcpdod yep, main fix is same...

**Pull request closed without merging**
